/**
 * Respuestas predefinidas de admisión — AR School Puente Alto.
 *
 * Fuente: AR_School_Respuestas_Kommo_v4.docx (versión 4). El texto se copió
 * tal cual; para cambiar una respuesta, edítala aquí o actualiza el documento
 * y vuelve a generar este archivo.
 *
 * - tipo "mensaje": se envía a la familia (los [CORCHETES] se completan a mano)
 * - tipo "nota": nota interna para el lead en Kommo, no se envía
 */

export interface Plantilla {
  id: string;
  seccion: string;
  titulo: string;
  texto: string;
  tipo: "mensaje" | "nota";
  /** Indicación de uso del documento (ej: "Usar solo cuando exista autorización interna") */
  nota: string | null;
  requiereAutorizacion: boolean;
}

export const PLANTILLAS: Plantilla[] = [
  {
    id: "1.1",
    seccion: "1. Primer contacto: que sepan quién escribe y por qué",
    titulo: "Publicidad / Play Group",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo Encina, coordinador de *AR School Global, sede Puente Alto*.\n\nTe escribo porque nos dejaste tus datos / nos hablaste a través de una de nuestras publicaciones solicitando información sobre nuestro *Play Group en Puente Alto*. 💙\n\nPara que puedas ubicarnos mejor:\n🌐 https://www.arschoolglobal.com/\n\nQuiero ayudarte personalmente con tu consulta. ¿Qué edad tiene tu pequeñito/a? Con eso te digo al tiro la alternativa que corresponde. 🦁",
  },
  {
    id: "1.2",
    seccion: "1. Primer contacto: que sepan quién escribe y por qué",
    titulo: "Publicidad / AR School Admisión",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo Encina, coordinador de *AR School Global, sede Puente Alto*.\n\nTe escribo porque nos dejaste tus datos solicitando información sobre nuestro *proceso de admisión*. 💙\n\nPara que puedas conocernos mejor:\n🌐 https://www.arschoolglobal.com/\n\n¿Me cuentas qué edad tiene tu hijo/a y para qué año estás buscando? Con eso te envío la información exacta de su nivel.",
  },
  {
    id: "1.3",
    seccion: "1. Primer contacto: que sepan quién escribe y por qué",
    titulo: "Reactivación de consulta antigua",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo Encina, de *AR School Global, sede Puente Alto*.\n\nHace un tiempo nos habías solicitado información para tu hijo/a y estoy retomando personalmente algunas consultas que quedaron pendientes. 💙\n\nPara que sepas desde dónde te escribo:\n🌐 https://www.arschoolglobal.com/\n\n¿Sigues buscando una alternativa educativa? Si es así, cuéntame su edad y te ayudo desde acá.",
  },
  {
    id: "1.4",
    seccion: "1. Primer contacto: que sepan quién escribe y por qué",
    titulo: "“¿De dónde me escriben?”",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 Te escribo desde *AR School Global, sede Puente Alto*.\n\nHace un tiempo nos dejaste tus datos / solicitaste información sobre admisión para tu hijo/a y por eso estamos retomando tu consulta.\n\nSomos un *Centro Educacional Alternativo* de Fundación Educacional ARM Global.\n\n🌐 https://www.arschoolglobal.com/\n📍 Av. José Manuel Irarrázaval 0565, Puente Alto.\n\nSoy Pablo Encina, coordinador de la sede, y feliz te ayudo personalmente desde acá 💙",
  },
  {
    id: "2.1",
    seccion: "2. Seguimiento cuando la persona deja de responder",
    titulo: "Primer seguimiento — 24 horas",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Paso nuevamente por acá desde *AR School Puente Alto* porque no quería que tu consulta quedara perdida.\n\n¿Sigues buscando una alternativa para tu hijo/a?\n\nSi es así, te envío valores, horarios y disponibilidad según su edad 💙",
  },
  {
    id: "2.2",
    seccion: "2. Seguimiento cuando la persona deja de responder",
    titulo: "Segundo seguimiento — 48 a 72 horas",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo, de *AR School Puente Alto*.\n\nQuería escribirte una vez más antes de cerrar tu consulta. Si todavía estás evaluando opciones para tu hijo/a, puedo ayudarte personalmente y también coordinar una visita para que conozcas nuestro proyecto antes de decidir. 💙\n\n¿Te gustaría que revisemos una opción para él/ella?",
  },
  {
    id: "2.3",
    seccion: "2. Seguimiento cuando la persona deja de responder",
    titulo: "Seguimiento con visita concreta — 3 a 5 días",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Esta semana estaré recibiendo familias en nuestra *sede AR School Puente Alto*.\n\nComo tú nos habías consultado por [PLAY GROUP / AR SCHOOL], quería dejarte la invitación antes de cerrar tu solicitud. 💙\n\nTengo disponibilidad el *[DÍA 1]* o el *[DÍA 2]* en la mañana. ¿Cuál te acomoda más?",
  },
  {
    id: "2.4",
    seccion: "2. Seguimiento cuando la persona deja de responder",
    titulo: "Último seguimiento — cierre amable",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo, de *AR School Puente Alto*.\n\nComo no he logrado tener respuesta, voy a dejar tu consulta cerrada por ahora para no llenarte de mensajes.\n\nSi más adelante vuelves a buscar una alternativa para tu hijo/a, escríbeme con toda confianza y retomamos desde donde quedamos. 💙\n\nUn abrazo,\nPablo Encina — AR School Puente Alto 🦁",
  },
  {
    id: "2.5",
    seccion: "2. Seguimiento cuando la persona deja de responder",
    titulo: "Reactivación posterior — 15 a 30 días",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo Encina, coordinador de *AR School Global, sede Puente Alto*.\n\nHace un tiempo nos habías solicitado información para tu hijo/a y quería saber cómo les fue finalmente.\n\n¿Ya encontraron una alternativa educativa o todavía están evaluando opciones?\n\nSi aún estás buscando, feliz revisamos nuevamente tu caso 💙",
  },
  {
    id: "3.1",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "4 años — Play Group",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Gracias [NOMBRE] 😊 Con *4 años*, [NOMBRE NIÑO/A] puede ingresar a nuestro *Play Group de AR School Puente Alto*. 💙\n\nTrabajamos con grupos pequeños y un acompañamiento bien cercano en esta etapa.\n\nPara orientarte bien, ¿estás buscando cupo *para este año o para 2027*? Con eso te envío horarios, valores y disponibilidad.",
  },
  {
    id: "3.2",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "5 años — Pre-School",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Súper 😊 Con *5 años*, [NOMBRE NIÑO/A] corresponde a nuestro nivel *Pre-School*. 💙\n\nEn esta etapa acompañamos el aprendizaje de manera cercana, fortaleciendo autonomía, lenguaje, pensamiento, habilidades y seguridad personal.\n\n¿Estás buscando cambiarlo/a ahora o estás evaluando una alternativa para el próximo año?",
  },
  {
    id: "3.3",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "6 años — Elementary",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¡Perfecto! 😊 Con *6 años*, [NOMBRE NIÑO/A] corresponde a nuestro nivel *Elementary* en AR School Puente Alto. 💙\n\nEn esta etapa buscamos que el estudiante no solo aprenda contenidos, sino que también desarrolle autonomía, habilidades, pensamiento y seguridad en su proceso.\n\n¿Actualmente está en 1° básico o estaría ingresando el próximo año?",
  },
  {
    id: "3.4",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "8 años — Elementary",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Perfecto 😊 Con *8 años*, [NOMBRE NIÑO/A] está dentro de nuestro nivel *Elementary*. 💙\n\nTrabajamos el aprendizaje académico con un acompañamiento más personalizado, buscando que cada estudiante comprenda, participe y avance respetando su propio ritmo.\n\n¿Para qué curso estás buscando ingreso el próximo año?",
  },
  {
    id: "3.5",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "12 años — Middle School",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Perfecto, gracias por contarme 😊 Con *12 años*, tu hija/o corresponde a nuestro nivel *Middle School*. 💙\n\nEn esta etapa seguimos trabajando los aprendizajes académicos, pero también autonomía, responsabilidad, pensamiento crítico, habilidades y liderazgo personal.\n\nSi quieres, te cuento cómo funciona específicamente para su curso y coordinamos una visita para que puedan conocer la modalidad en persona.",
  },
  {
    id: "3.6",
    seccion: "3. Respuestas según edad o nivel",
    titulo: "6° básico + continuidad a enseñanza media",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 Para *6° básico* sí tenemos continuidad dentro de nuestro programa, y también contamos con *High School*, que corresponde a la etapa de enseñanza media. 💙\n\nLa idea es que los estudiantes puedan avanzar dentro del mismo proyecto educativo sin tener que cambiar de modalidad al terminar básica.\n\nSi quieres, te puedo explicar cómo sería el proceso para 6° básico y cómo continúa después hacia High School. ¿Te gustaría que te envíe esa información?",
  },
  {
    id: "4.1",
    seccion: "4. Cuando vienen de colegio tradicional y preguntan por la modalidad",
    titulo: "Explicación completa de la modalidad",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 Te cuento un poquito para que puedas entender mejor nuestra modalidad.\n\n*AR School es un centro educativo alternativo.* A diferencia de un colegio tradicional, buscamos que el estudiante sea parte activa de su aprendizaje y entendemos que *no todos aprenden de la misma manera ni al mismo ritmo*. 💙\n\nTrabajamos los aprendizajes académicos, pero con un acompañamiento más personalizado, desarrollando también habilidades, autonomía, liderazgo y valores.\n\nAlgo importante que siempre explicamos con transparencia es que *no somos un colegio tradicional sujeto al Ministerio de Educación*.\n\nLos estudios se validan mediante *exámenes libres en Chile* o a través de nuestro convenio con *Home Life Academy de Estados Unidos*.\n\nSi tu hijo/a siempre ha estado en un colegio tradicional, lo ideal es que puedan venir a conocernos, porque viendo una jornada y conversando con nosotros se entiende mucho mejor la diferencia. 😊\n\n¿Qué edad tiene y en qué curso está actualmente? Así te explico cómo sería específicamente su ingreso y adaptación. 🦁",
  },
  {
    id: "4.2",
    seccion: "4. Cuando vienen de colegio tradicional y preguntan por la modalidad",
    titulo: "Modalidad — bloques cortos para enviar uno por uno",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "MENSAJE 1\nClaro 😊 Te cuento un poquito para que puedas entender mejor nuestra modalidad.\n\nMENSAJE 2\n*AR School es un centro educativo alternativo.* A diferencia de un colegio tradicional, buscamos que el estudiante sea parte activa de su aprendizaje y entendemos que *no todos aprenden de la misma manera ni al mismo ritmo*. 💙\n\nMENSAJE 3\nTrabajamos los aprendizajes académicos, pero con un acompañamiento más personalizado, desarrollando también habilidades, autonomía, liderazgo y valores.\n\nMENSAJE 4\nAlgo importante que siempre explicamos con transparencia es que *no somos un colegio tradicional sujeto al Ministerio de Educación*. Los estudios se validan mediante *exámenes libres en Chile* o a través de nuestro convenio con *Home Life Academy de Estados Unidos*.\n\nMENSAJE 5\nComo tu hijo/a siempre ha estado en un colegio tradicional, creo que lo mejor sería que puedan *venir a conocernos*. Viendo una jornada y conversando con nosotros se entiende mucho mejor la diferencia. 😊\n\n¿Qué edad tiene y en qué curso está actualmente? 🦁",
  },
  {
    id: "4.3",
    seccion: "4. Cuando vienen de colegio tradicional y preguntan por la modalidad",
    titulo: "Quiere información para conversarlo con su esposo/a",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro [NOMBRE] 😊 Entiendo perfecto. Te dejo un resumen bien claro para que también puedas conversarlo tranquila/o en casa con tu esposo/a. 💙\n\n*AR School es un centro educativo alternativo*, no un colegio tradicional. Nuestro enfoque busca que cada niño sea parte activa de su aprendizaje, entendiendo que *no todos aprenden de la misma manera ni al mismo ritmo*.\n\nTrabajamos los aprendizajes académicos, pero también ponemos mucho énfasis en *autonomía, habilidades, liderazgo, valores y acompañamiento personalizado*.\n\nTenemos un sello de *valores cristianos*, pero no existe ningún requisito religioso para ingresar.\n\nAlgo importante que siempre contamos con transparencia es que *AR School no funciona como un colegio tradicional sujeto al Ministerio de Educación*. Los estudios se pueden validar mediante *exámenes libres en Chile* o a través de nuestro convenio con *Home Life Academy de Estados Unidos*.\n\nMás que tratar de explicarte todo por WhatsApp, creo que sería muy bueno que *vengan los dos a conocer la sede*. Así pueden recorrer los espacios, resolver sus dudas y después conversarlo tranquilos en familia. 💙\n\n¿Qué día de la próxima semana les acomodaría venir juntos?",
  },
  {
    id: "4.4",
    seccion: "4. Cuando vienen de colegio tradicional y preguntan por la modalidad",
    titulo: "Resumen breve: “¿Qué es AR School?”",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 *AR School Global es un Centro Educacional Alternativo*.\n\nTrabajamos los aprendizajes académicos, pero con un enfoque más cercano y personalizado, desarrollando también autonomía, habilidades, liderazgo y valores. 💙\n\nNo buscamos que todos los estudiantes aprendan igual o al mismo ritmo.\n\nPuedes conocernos mejor acá:\n🌐 https://www.arschoolglobal.com/\n\nSi me cuentas la edad y curso de tu hijo/a, te explico cómo sería específicamente para él/ella.",
  },
  {
    id: "5.1",
    seccion: "5. Dos hermanos / más de un hijo",
    titulo: "Hijos de 5 y 8 años",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¡Qué linda etapa! 😊 Entonces tienes dos peques de *5 y 8 años*.\n\nEn nuestro caso podrían incorporarse a *Pre-School y Elementary* en AR School Puente Alto. 💙\n\nAlgo bonito de nuestro proyecto es que *ambos pueden crecer dentro de la misma comunidad educativa*, pero con un acompañamiento pensado para la etapa y ritmo de cada uno.\n\nNo buscamos que todos aprendan igual, sino conocer a cada estudiante y desarrollar sus habilidades, autonomía, valores y aprendizaje de manera cercana. 🦁\n\nComo son dos niños en etapas distintas, creo que vale mucho más la pena venir a conocerlo que explicarte todo solamente por WhatsApp.\n\nLa próxima semana estaré recibiendo familias en la sede. *¿Te acomoda más venir el lunes o el martes en la mañana?* 😊",
  },
  {
    id: "5.2",
    seccion: "5. Dos hermanos / más de un hijo",
    titulo: "Quiere detalles antes de visitar — Kinder + 4° básico",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 y me parece súper importante que quieras conocer bien *cómo trabajamos antes de tomar una decisión para tus hijos/as*.\n\nPara quien irá a *Kinder*, buscamos que aprenda a través de experiencias, participación y acompañamiento cercano, fortaleciendo autonomía, lenguaje, pensamiento y seguridad en esta etapa.\n\nY para quien irá a *4° básico*, el aprendizaje académico sigue siendo importante, pero buscamos que no sea solamente memorizar contenidos. Queremos que pueda comprender, participar, desarrollar autonomía, pensamiento crítico y descubrir sus propias habilidades, respetando también su ritmo de aprendizaje. 🦁\n\nNuestro modelo es más cercano y personalizado que el de un colegio tradicional.\n\nEn la visita podremos mostrarte los espacios, explicarte cómo sería la jornada de cada uno/a y responder todas las preguntas que necesites para que después puedan conversarlo tranquilos en familia. 💙",
  },
  {
    id: "6.1",
    seccion: "6. PIE, diagnósticos y necesidades de apoyo",
    titulo: "Pregunta por PIE",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Te cuento con transparencia 😊 Como *AR School es un centro educativo alternativo y no un colegio tradicional sujeto al Ministerio de Educación*, no funcionamos con un *PIE ministerial tradicional*.\n\nDe todas maneras, sí buscamos conocer las necesidades particulares de cada estudiante y evaluar cómo podemos acompañarlo/a de la mejor manera. 💙\n\nCuando existe un diagnóstico o necesidad específica, coordinamos una conversación con nuestra psicopedagoga para revisar el caso antes de avanzar.\n\nSi quieres, me puedes contar un poquito qué apoyo necesita tu hijo/a y así te oriento mejor.",
  },
  {
    id: "6.2",
    seccion: "6. PIE, diagnósticos y necesidades de apoyo",
    titulo: "Pregunta PIE + cantidad de alumnos por sala",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Perfecto, gracias por contarme 😊\n\nSobre *PIE*, como AR School funciona como un centro educativo alternativo, no trabajamos con PIE ministerial tradicional. Sin embargo, sí podemos evaluar las necesidades particulares de cada estudiante y conversar con nuestro equipo para ver cómo podemos acompañarlo/a de la mejor manera. 💙\n\nRespecto a la *cantidad de alumnos por sala en [NIVEL]*, prefiero confirmarte el número exacto antes de darte un dato incorrecto.\n\nSi quieres, podemos agendar una visita para conversar sobre tu hijo/a y resolver estas preguntas de manera más personalizada.\n\n¿Te acomoda más venir el lunes o el martes en la mañana? 😊",
  },
  {
    id: "6.3",
    seccion: "6. PIE, diagnósticos y necesidades de apoyo",
    titulo: "Diagnóstico o necesidad especial",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Gracias por contármelo, [NOMBRE] 💙 Es importante para nosotros conocer las necesidades de cada estudiante.\n\nAl completar la ficha de admisión puedes indicarlo y coordinaremos una conversación con nuestra psicopedagoga.\n\nLa idea es conocer bien a tu hijo/a y evaluar juntos si lo que ofrecemos se ajusta a lo que necesita, antes de tomar una decisión.",
  },
  {
    id: "7.1",
    seccion: "7. Valores, objeciones y facilidades",
    titulo: "Play Group — valores 2026",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 Te dejo la información de nuestro *Play Group — Sede Puente Alto*:\n\n🔹 *Jornada Completa — $260.000*\nLunes a jueves 8:00 a 18:00 hrs.\nViernes 8:00 a 17:00 hrs.\n\n🔹 *Media Jornada AM — $195.000*\nLunes a viernes 8:00 a 13:00 hrs.\n\n🔹 *Media Jornada PM — $195.000*\nLunes a jueves 13:00 a 18:00 hrs.\nViernes 13:00 a 17:00 hrs.\n\n💰 *Aporte inicial: $80.000*\n\nTrabajamos con grupos de 13 a 15 niños para entregar un acompañamiento cercano y personalizado. 💙\n\n¿Te gustaría venir a conocerlo? Puedo coordinarte una visita esta semana.",
  },
  {
    id: "7.2",
    seccion: "7. Valores, objeciones y facilidades",
    titulo: "AR School — aportes 2027",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Claro 😊 Para 2027, en nuestra sede de Puente Alto:\n\n💰 *Aporte inicial: $104.000*\n💙 *Aporte mensual: $220.500*\n\n🕐 *Horario*\nLunes, martes y jueves: 8:30 a 16:00 hrs.\nMiércoles y viernes: 8:30 a 13:40 hrs.\n\nMás que entregarte solo el valor, me gustaría que pudieras conocer qué hay detrás: cómo trabajamos, nuestros espacios y el acompañamiento que damos a cada estudiante.\n\n¿Te acomoda venir [DÍA 1] o [DÍA 2]? 🦁",
  },
  {
    id: "7.3",
    seccion: "7. Valores, objeciones y facilidades",
    titulo: "El aporte le parece alto",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Te entiendo, [NOMBRE] 😊 Es una decisión importante para cualquier familia.\n\nPor eso creo que más que mirar solamente el número, vale la pena conocer *cómo trabajamos, el tamaño de nuestros grupos y el acompañamiento que recibe cada estudiante*. 💙\n\nAntes de cerrar tu consulta, ¿el principal impedimento hoy es solamente el valor mensual?",
  },
  {
    id: "7.4",
    seccion: "7. Valores, objeciones y facilidades",
    titulo: "Apoyo interno por distancia / traslado",
    tipo: "mensaje",
    nota: "Usar solo cuando exista autorización interna para evaluar este tipo de atención.",
    requiereAutorizacion: true,
    texto: "Te entiendo totalmente 😊 Sabemos que el traslado desde [COMUNA] puede implicar un esfuerzo adicional.\n\nSi existe interés real en nuestro proyecto, puedo revisar internamente una *atención especial sobre el aporte mensual*, pensada en ayudar a compensar parte de ese gasto. 💙\n\nNo corresponde al pago de transporte, sino a una facilidad interna que podemos evaluar para que la distancia no sea lo que les impida conocernos.\n\n*¿Te parece que revise tu caso?*",
  },
  {
    id: "8.1",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "Invitación directa",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "[NOMBRE], me gustaría invitarte a conocer nuestra sede 😊\n\nAsí puedes recorrer los espacios, conocer cómo trabajamos y conversar con nosotros con calma sobre lo que estás buscando para tu hijo/a. 💙\n\nTengo disponibilidad el *[DÍA 1]* o el *[DÍA 2]*. ¿Cuál te acomoda más?",
  },
  {
    id: "8.2",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "Visita próxima semana",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¡Perfecto, [NOMBRE]! 😊\n\nMe gustaría invitarte a conocer nuestra sede la próxima semana, para que puedas recorrer los espacios, conocer un poco más de nuestra modalidad y resolver todas tus dudas con calma. 💙\n\nTengo disponibilidad el *lunes o martes*. ¿Cuál de los dos días te acomoda más? 🦁",
  },
  {
    id: "8.3",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "Ofrecer dos horarios",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Súper 😊 Ese día tengo disponibilidad en dos horarios:\n\n🕐 *[HORA 1]*\n🕐 *[HORA 2]*\n\n¿Cuál te acomoda más para dejarte agendado/a?",
  },
  {
    id: "8.4",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "Confirmación de visita",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¡Perfecto, [NOMBRE]! 😊 Entonces te esperamos en *AR School Puente Alto* el *[DÍA] a las [HORA]*.\n\n📍 Av. José Manuel Irarrázaval 0565, Puente Alto.\n\nPuedes venir con tu hijo/a para que también conozca el espacio 💙\n\nSi surge algún imprevisto, me avisas y lo reagendamos sin problema.",
  },
  {
    id: "8.5",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "Post-visita",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Soy Pablo.\n\nQuería agradecerles por venir a conocernos. Fue muy lindo recibirlos a ti y a [NOMBRE NIÑO/A] 💙\n\nPara nosotros es importante saber cómo vivieron la experiencia.\n\n*¿Con qué sensación se fueron después de conocer la sede?*",
  },
  {
    id: "8.6",
    seccion: "8. Visitas: llevar la conversación al siguiente paso",
    titulo: "No llegó a la visita",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Espero que estén bien.\n\nVi que finalmente no pudieron llegar a la visita que habíamos coordinado. No te preocupes, sé que pueden surgir imprevistos.\n\nSi todavía quieres conocernos, puedo dejarte una nueva hora.\n\n¿Te acomoda más *[DÍA 1]* o *[DÍA 2]*? 💙",
  },
  {
    id: "9.1",
    seccion: "9. Proceso de admisión",
    titulo: "Enviar formulario",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¡Perfecto! 😊 Te dejo el formulario de admisión para [NOMBRE NIÑO/A]:\n\n👉 https://app.arschoolglobal.com/admision\n\nSon solo unos minutos. Te pedirá tus datos como apoderado/a y los datos de tu hijo/a.\n\nCuando lo completes, avísame por acá y yo mismo hago seguimiento al proceso 💙",
  },
  {
    id: "9.2",
    seccion: "9. Proceso de admisión",
    titulo: "Recordatorio de formulario",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Hola [NOMBRE] 😊 Quería saber si alcanzaste a completar el formulario de admisión de [NOMBRE NIÑO/A].\n\nSi tuviste algún problema o te quedó alguna duda, escríbeme y te ayudo personalmente 💙\n\n👉 https://app.arschoolglobal.com/admision",
  },
  {
    id: "10.1",
    seccion: "10. Situaciones sensibles y recuperación de confianza",
    titulo: "Reclamo por demora / problemas del sistema",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "[NOMBRE], entiendo totalmente tu molestia y tienes razón en sentirte así. 🙏\n\nDurante ese período tuvimos *algunos inconvenientes en nuestro sistema de admisión y seguimiento*, y lamentablemente algunas consultas no fueron gestionadas como correspondía.\n\n*Te pido disculpas personalmente por eso.* No es la experiencia que queremos entregar a las familias que se acercan a AR School.\n\nHoy estoy retomando directamente estos casos.\n\nSi todavía estás buscando una alternativa para tu hijo/a, me gustaría ayudarte personalmente desde acá. ¿Qué edad tiene y para qué año estás buscando? 💙",
  },
  {
    id: "10.2",
    seccion: "10. Situaciones sensibles y recuperación de confianza",
    titulo: "Ya encontró otra alternativa",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Gracias por contarme, [NOMBRE] 😊 Me alegra saber que pudieron encontrar una alternativa para [NOMBRE NIÑO/A].\n\nLes deseo de corazón que sea una muy linda etapa para ustedes 💙\n\nY si en algún momento necesitan volver a conversar con nosotros, las puertas de AR School quedan abiertas. 🦁",
  },
  {
    id: "10.3",
    seccion: "10. Situaciones sensibles y recuperación de confianza",
    titulo: "No está interesado/a",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "Perfecto, [NOMBRE] 😊 Gracias por responderme.\n\nDejo tu consulta cerrada para no seguir enviándote mensajes.\n\nSi más adelante necesitas información o quieres volver a conocernos, puedes escribirme directamente por acá 💙\n\nQue estén muy bien.",
  },
  {
    id: "11.1",
    seccion: "11. Notas internas para Kommo",
    titulo: "Contactado por interno — esperando respuesta",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Contacto realizado por WhatsApp directo desde la sede Puente Alto. Se entregó contexto de AR School y motivo del contacto. Pendiente de respuesta para continuar seguimiento.",
  },
  {
    id: "11.2",
    seccion: "11. Notas internas para Kommo",
    titulo: "Sin respuesta después de seguimientos",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Se realizaron seguimientos de admisión sin obtener respuesta. Se cierra la gestión por ahora, dejando posibilidad de reactivación futura.",
  },
  {
    id: "11.3",
    seccion: "11. Notas internas para Kommo",
    titulo: "No continúa por presupuesto",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Se entregó toda la información y facilidades disponibles para avanzar. La persona decide no continuar debido a que el aporte se encuentra fuera de su presupuesto actual.",
  },
  {
    id: "11.4",
    seccion: "11. Notas internas para Kommo",
    titulo: "No continúa por distancia",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Familia manifiesta que la distancia hacia la sede es el principal impedimento para continuar. Se entregaron/evaluaron alternativas disponibles y se cierra la gestión por ahora.",
  },
  {
    id: "11.5",
    seccion: "11. Notas internas para Kommo",
    titulo: "Visita realizada — familia evaluando",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Familia realizó visita presencial a la sede. Se entregó información del proyecto educativo, modalidad, aportes y proceso de admisión. Quedan en evaluación familiar. Programar seguimiento.",
  },
  {
    id: "11.6",
    seccion: "11. Notas internas para Kommo",
    titulo: "Quiere conversarlo con su esposo/a",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Apoderado/a solicita mayor claridad sobre la modalidad para conversarlo en familia. Se entrega resumen del proyecto educativo y se propone visita conjunta. Pendiente de confirmación.",
  },
  {
    id: "11.7",
    seccion: "11. Notas internas para Kommo",
    titulo: "Interés por dos hermanos",
    tipo: "nota",
    nota: null,
    requiereAutorizacion: false,
    texto: "Familia evalúa ingreso de dos hermanos en niveles distintos. Se explicó continuidad dentro de la misma comunidad educativa y acompañamiento según etapa. Pendiente visita / definición.",
  },
  {
    id: "12.1",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Edad",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Qué edad tiene tu hijo/a? Con eso te oriento al tiro 💙",
  },
  {
    id: "12.2",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Año",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Estás buscando para este año o para 2027?",
  },
  {
    id: "12.3",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Curso",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿En qué curso está actualmente?",
  },
  {
    id: "12.4",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Visita",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Te acomoda más lunes o martes? 😊",
  },
  {
    id: "12.5",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Horario",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Te queda mejor a las 10:00 o a las 11:30?",
  },
  {
    id: "12.6",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Admisión",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Te envío el formulario para avanzar?",
  },
  {
    id: "12.7",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Interés",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Sigues buscando una alternativa para tu hijo/a?",
  },
  {
    id: "12.8",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Objeción",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿El principal impedimento hoy es solamente el valor mensual?",
  },
  {
    id: "12.9",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Apoyo",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Te parece que revise tu caso?",
  },
  {
    id: "12.10",
    seccion: "12. Cierres rápidos que generan respuesta",
    titulo: "Familia",
    tipo: "mensaje",
    nota: null,
    requiereAutorizacion: false,
    texto: "¿Qué día les acomodaría venir juntos a conocer la sede?",
  },
];

/** Datos de referencia y recordatorios internos del documento. */
export const DATOS_REFERENCIA = "AR SCHOOL GLOBAL\n🌐 https://www.arschoolglobal.com/\n\n📍 Sede Puente Alto\nAv. José Manuel Irarrázaval 0565, Puente Alto\n\n📲 WhatsApp Admisión\n+56 9 3690 2642\n\n📝 Formulario de admisión\nhttps://app.arschoolglobal.com/admision\n\nNiveles de referencia:\n• Play Group: 2 a 5 años\n• Pre-School: 5 años\n• Elementary: 6 a 8 años\n• Middle School: 9 a 13 años\n• High School: 14 a 17 años\n\nRECORDATORIOS INTERNOS:\n• No prometer becas, descuentos o apoyos sin autorización.\n• No inventar cantidad de alumnos por sala en niveles donde no esté confirmado.\n• Desde los 6 años, explicar con transparencia la modalidad de validación de estudios.\n• Siempre que sea posible, cerrar con una pregunta concreta.";
